### ISSUE TITLE
フロントエンドフレームワークの選定

### ISSUE THREAD

**Issue by Lagyu** [Lagyu/freeGoToEat#4]
NextJSとかGatsbyとかを適当に試してみる→実装

**Comment by ogadra** [comment]
・デザインの大枠を決める

**Comment by ogadra** [comment]
Gatsby vs Next.js問題ですが、今回はGatsbyを使用したいと考えています
次のタスクはGatsby Tutorialです

**Comment by ogadra** [comment]
React and NEXT.jsで作り始めます。
